using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using sheduler.Models;

namespace sheduler.Controllers
{
    //[Authorize]
    [HandleError]
    public class ResponsesController : Controller
    {
        private MyDosa_dbEntities1 db = new MyDosa_dbEntities1();

        // GET: Responses
        public ActionResult Index()
        {
            var responses = db.Responses.Include(r => r.Inquiry);
            return View(responses.ToList());
        }

        // GET: Responses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Responses.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return View(response);
        }

        // GET: Responses/Create
        public ActionResult Create()
        {
            ViewBag.Inquirery_id = new SelectList(db.Inquiries, "Inquirery_id", "inquirry");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResponseId,Inquirery_id,Response1,DatetimeOfReply")] Response response)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var id = Session["userid"].ToString();
               
                    //GENERATE DATA TO SEND MAIL
                    var inqid = response.Inquirery_id;

                    var userid = db.Inquiries.Where(a=>a.Inquirery_id == inqid).Select(a=>a.UserId).FirstOrDefault();
                    
                    if (userid !=null && inqid > 0)
                    {
                        var username = db.Students.Where(a => a.AccessNumber == userid).Select(a => a.UserName).FirstOrDefault();
                        var useremail = db.Students.Where(a => a.AccessNumber == userid).Select(a => a.Email).FirstOrDefault();
                        var PostedDate = db.Inquiries.Where(a => a.Inquirery_id == inqid).Select(a => a.Dateposteed).FirstOrDefault();
                        var inq = db.Inquiries.Where(a => a.Inquirery_id == inqid).Select(a => a.inquirry).FirstOrDefault();
                        var adminusername = db.Students.Where(a => a.AccessNumber == id).Select(a => a.UserName).FirstOrDefault();
                        response.DatetimeOfReply = DateTime.Now;
                        db.Responses.Add(response);
                        db.SaveChanges();
                        TempData["success"] = "SUCCESSFULY RESPONDED";
                        Send_Response_Email(useremail, username, adminusername, PostedDate, inq,response.Response1);
                    }
                    else
                    {
                        TempData["error"] = "ERROR VALIDATING SENDER DETAILS";
                    }

                    return RedirectToAction("Index");
                }

            }catch(Exception e)
            {
                TempData["errorsaving"]  = e.Message;
            }
            ViewBag.Inquirery_id = new SelectList(db.Inquiries, "Inquirery_id", "inquirry", response.Inquirery_id);
            return View(response);
        }

        public void Send_Response_Email(string emailId, string username, string adminusername, DateTime PostedDate, string inq,string response)
        {
            var fromEmail = new MailAddress("testmarvinug@gmail.com", "UGANDA CHRISTIAN UNIVERSITY(DOSA)");
            var toEmail = new MailAddress(emailId);
            //this password is generated by u in ur email account
            var fromEmailPassword = "kcywjucbmujbrycc";

            var subject = "INQUIRY UPDATE";
            var body1 = "Grettings" + username + ", " + "<br/>" + "<br/>"
                +"With Reference to your inquiry that was posted on  " + PostedDate + " To OurTeam, We are glad to inform you that we recieved it and we have presponded to it " + "<br/> <br/>"
                 + "YOUR INQUIRY <br/>"
                 +inq+ "<br/><br/>"
                 + "RESPONSE <br/>"
                   + response + ".<br/> <br/>" +
               
           "BY " + "<br/>" + adminusername;

            var smtp = new SmtpClient("smtp.gmail.com")
            {
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new System.Net.NetworkCredential(fromEmail.Address, fromEmailPassword),
            };

            string body = string.Empty;
            var root = AppDomain.CurrentDomain.BaseDirectory;

            using (var reader = new System.IO.StreamReader(root + @"/Template/html/email.html"))
            {
                string readFile = reader.ReadToEnd();
                string StrContent = string.Empty;
                StrContent = readFile;
                //Assing the field values in the template
                StrContent = StrContent.Replace("[body]", body1);

                body = StrContent.ToString();
            }

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
                //Fetching Email Body Text from EmailTemplate File.  
            })
                try
                {
                    smtp.Send(message);
                }
                catch (Exception e)
                {
                    TempData["error"] = e.Message;
                }
        }

        [NonAction]
        public bool responseExixts(int id)
        {
             var v = db.Responses.Where(a => a.ResponseId == id).FirstOrDefault();
                return v != null;
            
        }
        // GET: Responses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Responses.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            ViewBag.Inquirery_id = new SelectList(db.Inquiries, "Inquirery_id", "inquirry", response.Inquirery_id);
            return View(response);
        }

        // POST: Responses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResponseId,Inquirery_id,Response1,DatetimeOfReply")] Response response)
        {
            if (ModelState.IsValid)
            {
                db.Entry(response).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Inquirery_id = new SelectList(db.Inquiries, "Inquirery_id", "inquirry", response.Inquirery_id);
            return View(response);
        }

        // GET: Responses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = db.Responses.Find(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return View(response);
        }

        // POST: Responses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Response response = db.Responses.Find(id);
            db.Responses.Remove(response);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
