//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheduler.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

    public partial class Event
    {
[Display(Name = "EVENT")]
        public int EventID { get; set; }
        [Display(Name = "TRAVEL SUBJECT")]
        [MaxLength(100, ErrorMessage = "invalid description length")]
        public string Subject { get; set; }

        [Display(Name = " TRAVEL DESCRIPTION")]
        [DataType(DataType.MultilineText)]
       
        [MinLength(100, ErrorMessage = "invalid description length")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Body Content field required")]
        public string Description { get; set; }
        [Display(Name = "SET OFF TIME")]
        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = " setofftime field required")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Start { get; set; }
        [Display(Name = "ESTIMATED ARRIVAL TIME")]
        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = " arrival time field required")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> End { get; set; }
        public string ThemeColor { get; set; }
        public bool IsFullDay { get; set; }
        [Display(Name = "STUDENT ACCESS NUMBER")]
        public string userid { get; set; }
    }
}
