//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int Guestid { get; set; }
        public string Guest_name { get; set; }
        public string Guest_email { get; set; }
        public string Passcode { get; set; }
    }
}
