//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int user_id { get; set; }
        public string Access_No { get; set; }
        public Nullable<System.DateTime> visitDate { get; set; }
        public string IpAdrress { get; set; }
        public string DeviceUsed { get; set; }
        public Nullable<System.TimeSpan> TimeAccessed { get; set; }
        public Nullable<System.TimeSpan> LastSeenTime { get; set; }
    }
}
