//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Userroles = new HashSet<Userrole>();
        }
    
        public string AccessNumber { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public int Course_code { get; set; }
        public int sem_id { get; set; }
        public int Year_Id { get; set; }
        public int campus_id { get; set; }
        public string Country { get; set; }
        public string Passcode { get; set; }
        public string Password { get; set; }
    
        public virtual Campus_Branches Campus_Branches { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual semester semester { get; set; }
        public virtual UserLocation UserLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Userrole> Userroles { get; set; }
        public virtual Year Year { get; set; }
    }
}
